# Balance-Scale 

In [13]:
import numpy as np 
import pandas as pd #Verinin okunması ve işlenmesi için pandas kütüphanesi kullanılır
df = pd.read_csv('../dataset/balance-scale.data')

In [14]:
df.head() 

Class   L-Weight  L-Distance  R-Weight  R-Distance
0     B          1           1         1           1
1     R          1           1         1           2
2     R          1           1         1           3
3     R          1           1         1           4
4     R          1           1         1           5

In [15]:
R,L,B = df['Class'].value_counts()
print(R,L,B)

288 288 49


In [16]:
print("Zerorule :",R/(R+L+B)); #ZeroRule hesaplanır

Zerorule : 0.4608


In [17]:
y = df[['Class']] #Tahmin edilecek sütun alınır
X = df.drop(['Class'], axis = 1) #Tahmin edilecek sütun harici özellik sütunları alınır

In [18]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [19]:
import time

### Decision Tree Algorithm

In [20]:
from sklearn.tree import DecisionTreeClassifier #train
classifier = DecisionTreeClassifier(max_depth=5, random_state =  42)
start = time.time()
classifier.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.008002758026123047s


In [21]:
results =cross_val_score(classifier, x_train, y_train, cv=5) 
results

array([0.72619048, 0.78571429, 0.77380952, 0.77108434, 0.75903614])

In [22]:
np.average(results)

0.7631669535283993

In [23]:
results.std()

0.020340378149692518

### KNN Algorithm

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
start = time.time()
knn= knn.fit(x_train,y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.010102272033691406s


In [75]:
results =cross_val_score(knn, x_train, y_train.values.ravel(), cv=5) 
results

array([0.83333333, 0.85714286, 0.85714286, 0.85542169, 0.8313253 ])

In [76]:
np.average(results)

0.8468732071141709

In [77]:
results.std()

0.011908597630478062

### SVM Algorithm

In [24]:
from sklearn import svm
svm = svm.SVC() 
start = time.time()
svm.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.016003847122192383s


In [25]:
results =cross_val_score(svm, x_train, y_train.values.ravel(), cv=5) 
results

array([0.88095238, 0.89285714, 0.9047619 , 0.92771084, 0.93975904])

In [26]:
np.average(results)

0.9092082616179

In [27]:
results.std()

0.021731172642108706

### Random Forest Algorithm

In [80]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
start = time.time()
rfc.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.21403074264526367s


In [81]:
results =cross_val_score(rfc, x_train, y_train.values.ravel(), cv=5) 
results

array([0.82142857, 0.83333333, 0.85714286, 0.86746988, 0.85542169])

In [82]:
np.average(results)

0.8469592656339644

In [83]:
results.std()

0.016932133750285377