# Chess (King-Rook vs. King-Pawn) 

In [1]:
import numpy as np 
import pandas as pd #Verinin okunması ve işlenmesi için pandas kütüphanesi kullanılır
df = pd.read_csv('../dataset/kr-vs-kp.data')

In [2]:
df.head() 

c1 c2 c3 c4 c5 c6 c7 c8 c9 c10  ... c28 c29 c30 c31 c32 c33 c34 c35 c36  c37
0  f  f  f  f  f  f  f  f  f   f  ...   f   f   f   f   f   f   t   t   n  won
1  f  f  f  f  t  f  f  f  f   f  ...   f   f   f   f   f   f   t   t   n  won
2  f  f  f  f  t  f  t  f  f   f  ...   f   f   f   f   f   f   t   t   n  won
3  f  f  f  f  f  f  f  f  t   f  ...   f   f   f   f   f   f   t   t   n  won
4  f  f  f  f  f  f  f  f  f   f  ...   f   f   f   f   f   f   t   t   n  won

[5 rows x 37 columns]

In [3]:
won,nowin = df['c37'].value_counts()
print(won,nowin)

1669 1527


In [4]:
print("Zerorule :",won/(won+nowin)); #ZeroRule hesaplanır

Zerorule : 0.522215269086358


In [5]:
df = pd.get_dummies(df,drop_first = True)
df.head()
y = df[['c37_won']]
X = df.drop(['c37_won'], axis = 1)

In [6]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [7]:
import time

### Decision Tree Algorithm

In [8]:
from sklearn.tree import DecisionTreeClassifier #train
classifier = DecisionTreeClassifier(max_depth=5, random_state =  42)
start = time.time()
classifier.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.009019613265991211s


In [9]:
results =cross_val_score(classifier, x_train, y_train, cv=5) 
results

array([0.94871795, 0.93925234, 0.95327103, 0.95560748, 0.92757009])

In [10]:
np.average(results)

0.9448837766594776

In [11]:
results.std()

0.010310396181310992

### KNN Algorithm

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
start = time.time()
knn= knn.fit(x_train,y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.005997419357299805s


In [13]:
results =cross_val_score(knn, x_train, y_train.values.ravel(), cv=5) 
results

array([0.94871795, 0.94158879, 0.94859813, 0.92523364, 0.93224299])

In [14]:
np.average(results)

0.9392763000239637

In [15]:
results.std()

0.009252593707440408

### SVM Algorithm

In [8]:
from sklearn import svm
svm = svm.SVC() 
start = time.time()
svm.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.10800719261169434s


In [9]:
results =cross_val_score(svm, x_train, y_train.values.ravel(), cv=5) 
results

array([0.98368298, 0.96728972, 0.97429907, 0.98364486, 0.96028037])

In [10]:
np.average(results)

0.9738394004749145

In [11]:
results.std()

0.009165151147675825

### Random Forest Algorithm

In [18]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
start = time.time()
rfc.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.2890450954437256s


In [19]:
results =cross_val_score(rfc, x_train, y_train.values.ravel(), cv=5) 
results

array([0.995338  , 0.97663551, 0.98831776, 0.98598131, 0.97429907])

In [20]:
np.average(results)

0.9841143280395617

In [21]:
results.std()

0.007738180378833358