# Dermatology Veri Seti Karşılaştırılması

In [1]:
import numpy as np 
import pandas as pd #Verinin okunması ve işlenmesi için pandas kütüphanesi kullanılır
df = pd.read_csv('../dataset/dermatology.data')

In [2]:
df.head() 

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  ...  c26  c27  c28  c29  c30  c31  \
0   2   2   0   3   0   0   0   0   1    0  ...    0    0    3    0    0    0   
1   3   3   3   2   1   0   0   0   1    1  ...    0    0    0    0    0    0   
2   2   1   2   3   1   3   0   3   0    0  ...    0    2    3    2    0    0   
3   2   2   2   0   0   0   0   0   3    2  ...    3    0    0    0    0    0   
4   2   3   2   2   2   2   0   2   0    0  ...    2    3    2    3    0    0   

   c32  c33  c34  c35  
0    1    0   55    2  
1    1    0    8    1  
2    2    3   26    3  
3    3    0   40    1  
4    2    3   45    3  

[5 rows x 35 columns]

In [3]:
df['c35'].value_counts()

1    112
3     72
2     61
5     52
4     49
6     20
Name: c35, dtype: int64

In [4]:
print("Zerorule :",112/df['c35'].value_counts().sum()); #ZeroRule hesaplanır

Zerorule : 0.30601092896174864


In [5]:
df=df.replace('?',0)
y = df[['c35']]
X = df.drop(['c35'], axis = 1)

In [6]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [7]:
import time

### Decision Tree Algorithm

In [8]:
from sklearn.tree import DecisionTreeClassifier #train
classifier = DecisionTreeClassifier(max_depth=5, random_state =  42)
start = time.time()
classifier.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.007000923156738281s


In [9]:
results =cross_val_score(classifier, x_train, y_train, cv=5) 
results

array([0.91836735, 0.95918367, 0.95918367, 0.93877551, 0.89795918])

In [10]:
np.average(results)

0.9346938775510203

In [11]:
results.std()

0.023799803652429778

### KNN Algorithm

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
start = time.time()
knn= knn.fit(x_train,y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.005999565124511719s


In [13]:
results =cross_val_score(knn, x_train, y_train.values.ravel(), cv=5) 
results

array([0.83673469, 0.89795918, 0.81632653, 0.7755102 , 0.73469388])

In [14]:
np.average(results)

0.8122448979591838

In [15]:
results.std()

0.05536595904592055

### SVM Algorithm

In [8]:
from sklearn import svm
svm = svm.SVC() 
start = time.time()
svm.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.013009071350097656s


In [9]:
results =cross_val_score(svm, x_train, y_train.values.ravel(), cv=5) 
results

array([0.69387755, 0.69387755, 0.67346939, 0.67346939, 0.59183673])

In [10]:
np.average(results)

0.6653061224489796

In [11]:
results.std()

0.03785150406324777

### Random Forest Algorithm

In [18]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
start = time.time()
rfc.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.21703171730041504s


In [19]:
results =cross_val_score(rfc, x_train, y_train.values.ravel(), cv=5) 
results

array([0.95918367, 0.97959184, 0.97959184, 0.95918367, 0.95918367])

In [20]:
np.average(results)

0.9673469387755101

In [21]:
results.std()

0.00999791731748237