# Hayes-Roth Veri Seti Karşılaştırılması

In [1]:
import numpy as np 
import pandas as pd #Verinin okunması ve işlenmesi için pandas kütüphanesi kullanılır
df = pd.read_csv('../dataset/hayes-roth.data')

In [2]:
df.head() 

name  hobby  age  educational level  marital status  class
0    92      2    1                  1               2      1
1    10      2    1                  3               2      2
2    83      3    1                  4               1      3
3    61      2    4                  2               2      3
4   107      1    1                  3               4      3

In [3]:
a,b,c = df['class'].value_counts()
print(a,b,c)

51 51 30


In [4]:
print("Zerorule :",a/(a+b+c));

Zerorule : 0.38636363636363635


In [5]:
y = df[['class']]
X = df.drop(['class'], axis = 1)

In [6]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [7]:
import time

### Decision Tree Algorithm

In [8]:
from sklearn.tree import DecisionTreeClassifier #train
classifier = DecisionTreeClassifier(max_depth=5, random_state =  42)
start = time.time()
classifier.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.005998134613037109s


In [9]:
results =cross_val_score(classifier, x_train, y_train, cv=5) 
results

array([0.88888889, 0.88888889, 0.66666667, 0.70588235, 0.52941176])

In [10]:
np.average(results)

0.7359477124183006

In [11]:
results.std()

0.13794411459631808

### KNN Algorithm

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
start = time.time()
knn= knn.fit(x_train,y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.00400233268737793s


In [13]:
results =cross_val_score(knn, x_train, y_train.values.ravel(), cv=5) 
results

array([0.33333333, 0.38888889, 0.33333333, 0.29411765, 0.35294118])

In [14]:
np.average(results)

0.3405228758169935

In [15]:
results.std()

0.030823074830200255

### SVM Algorithm

In [8]:
from sklearn import svm
svm = svm.SVC() 
start = time.time()
svm.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.0003871917724609375s


In [9]:
results =cross_val_score(svm, x_train, y_train.values.ravel(), cv=5) 
results

array([0.38888889, 0.38888889, 0.38888889, 0.41176471, 0.52941176])

In [10]:
np.average(results)

0.4215686274509804

In [11]:
results.std()

0.054644588146610405

### Random Forest Algorithm

In [18]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
start = time.time()
rfc.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.27423858642578125s


In [19]:
results =cross_val_score(rfc, x_train, y_train.values.ravel(), cv=5) 
results

array([0.83333333, 0.83333333, 0.72222222, 0.76470588, 0.76470588])

In [20]:
np.average(results)

0.7836601307189542

In [21]:
results.std()

0.043423490828426406