# Balance-Scale 

In [1]:
import numpy as np 
import pandas as pd #Verinin okunması ve işlenmesi için pandas kütüphanesi kullanılır
df = pd.read_csv('../dataset/lymphography.data')

In [2]:
df.head() 

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c11  c12  c13  c14  c15  c16  c17  \
0   3   4   2   1   1   1   1   1   2    1    2    2    2    4    8    1    1   
1   2   3   2   1   1   2   2   1   2    1    3    3    2    3    4    2    2   
2   3   3   2   2   2   2   2   2   2    1    4    3    3    4    8    3    2   
3   3   3   1   1   1   1   2   1   2    1    3    3    4    4    4    3    1   
4   2   3   1   1   1   1   1   1   1    1    2    2    4    3    5    1    2   

   c18  c19  
0    2    2  
1    2    2  
2    2    7  
3    2    6  
4    2    1

In [3]:
a,b,c,d= df['c1'].value_counts()
print(a,b,c,d)

81 61 4 2


In [4]:
print("Zerorule :",a/(a+b+c+d)); #ZeroRule hesaplanır

Zerorule : 0.5472972972972973


In [5]:
y = df[['c1']]
X = df.drop(['c1'], axis = 1)

In [6]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [7]:
import time

### Decision Tree Algorithm

In [8]:
from sklearn.tree import DecisionTreeClassifier #train
classifier = DecisionTreeClassifier(max_depth=5, random_state =  42)
start = time.time()
classifier.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.005997657775878906s


In [9]:
results =cross_val_score(classifier, x_train, y_train, cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.9       , 0.8       , 0.95      , 0.75      , 0.68421053])

In [10]:
np.average(results)

0.8168421052631579

In [11]:
results.std()

0.09694216798441224

### KNN Algorithm

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
start = time.time()
knn= knn.fit(x_train,y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.004000186920166016s


In [13]:
results =cross_val_score(knn, x_train, y_train.values.ravel(), cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.8       , 0.65      , 0.85      , 0.8       , 0.68421053])

In [14]:
np.average(results)

0.756842105263158

In [15]:
results.std()

0.07628129892114417

### SVM Algorithm

In [8]:
from sklearn import svm
svm = svm.SVC() 
start = time.time()
svm.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.009867429733276367s


In [11]:
results =cross_val_score(svm, x_train, y_train.values.ravel(), cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.8       , 0.75      , 0.85      , 0.85      , 0.63157895])

In [12]:
np.average(results)

0.7763157894736843

In [13]:
results.std()

0.08131536365073312

### Random Forest Algorithm

In [18]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
start = time.time()
rfc.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.18900775909423828s


In [19]:
results =cross_val_score(rfc, x_train, y_train.values.ravel(), cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.85      , 0.85      , 0.9       , 0.9       , 0.73684211])

In [20]:
np.average(results)

0.8473684210526315

In [21]:
results.std()

0.05961557364060684