# Nursery Veri Seti Karşılaştırılması

In [1]:
import numpy as np 
import pandas as pd #Verinin okunması ve işlenmesi için pandas kütüphanesi kullanılır
df = pd.read_csv('../dataset/nursery.data')

In [2]:
df.head() 

c1      c2        c3 c4          c5          c6             c7  \
0  usual  proper  complete  1  convenient  convenient        nonprob   
1  usual  proper  complete  1  convenient  convenient        nonprob   
2  usual  proper  complete  1  convenient  convenient        nonprob   
3  usual  proper  complete  1  convenient  convenient  slightly_prob   
4  usual  proper  complete  1  convenient  convenient  slightly_prob   

            c8         c9  
0  recommended   priority  
1     priority   priority  
2    not_recom  not_recom  
3  recommended  not_recom  
4     priority   priority

In [3]:
t1,t2,t3,t4 = df['c9'].value_counts()
print(t1,t2,t3,t4)

4321 4267 4044 328


In [4]:
print("Zerorule :",t1/(t1+t2+t3+t4)) #ZeroRule hesaplanır

Zerorule : 0.3334104938271605


In [5]:
X = pd.get_dummies(df[['c1','c2','c3','c4','c5','c6','c7','c8']],drop_first = True) 
df.replace('negative',0,inplace=True) 
df.replace('positive',1,inplace=True) 
y = df.iloc[:,8].values 

In [6]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [7]:
import time

### Decision Tree Algorithm

In [10]:
from sklearn.tree import DecisionTreeClassifier #train
classifier = DecisionTreeClassifier(max_depth=5, random_state =  42)
start = time.time()
classifier.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.023001432418823242s


In [11]:
results =cross_val_score(classifier, x_train, y_train, cv=5) 
results

array([0.83419689, 0.83592401, 0.82959125, 0.85426267, 0.83410138])

In [12]:
np.average(results)

0.8376152405360161

In [13]:
results.std()

0.008583868811017636

### KNN Algorithm

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
start = time.time()
knn= knn.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.010998249053955078s


In [19]:
results =cross_val_score(knn, x_train, y_train, cv=5) 
results

array([0.90213011, 0.90616005, 0.89982729, 0.91301843, 0.90264977])

In [20]:
np.average(results)

0.9047571293267433

In [21]:
results.std()

0.004601366032930616

### SVM Algorithm

In [8]:
from sklearn import svm
svm = svm.SVC() 
start = time.time()
svm.fit(x_train, y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 2.062554359436035s


In [9]:
results =cross_val_score(svm, x_train, y_train, cv=5) 
results

array([0.99194013, 0.99251583, 0.99136442, 0.99135945, 0.98790323])

In [10]:
np.average(results)

0.9910166105553037

In [11]:
results.std()

0.0016144485392623135

### Random Forest Algorithm

In [27]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
start = time.time()
rfc.fit(x_train, y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.784308671951294s


In [28]:
results =cross_val_score(rfc, x_train, y_train, cv=5) 
results

array([0.96776051, 0.97294185, 0.96142775, 0.97177419, 0.96601382])

In [29]:
np.average(results)

0.9679836255634349

In [30]:
results.std()

0.004143955767015264