# Poker-Hand-Training-True Veri Seti Karşılaştırılması

In [1]:
import numpy as np 
import pandas as pd #Verinin okunması ve işlenmesi için pandas kütüphanesi kullanılır
df = pd.read_csv('../dataset/poker-hand-training-true.data')

In [2]:
df.head() 

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c11
0   1  10   1  11   1  13   1  12   1    1    9
1   2  11   2  13   2  10   2  12   2    1    9
2   3  12   3  11   3  13   3  10   3    1    9
3   4  10   4  11   4   1   4  13   4   12    9
4   4   1   4  13   4  12   4  11   4   10    9

In [3]:
df['c11'].value_counts()

0    12493
1    10599
2     1206
3      513
4       93
5       54
6       36
7        6
9        5
8        5
Name: c11, dtype: int64

In [4]:
print("ZeroRule : ",12493/df['c11'].value_counts().sum()); #ZeroRule hesaplanır

ZeroRule :  0.4995201919232307


In [5]:
y = df[['c11']]
X = df.drop(['c11'], axis = 1)

In [6]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [7]:
import time

### Decision Tree Algorithm

In [8]:
from sklearn.tree import DecisionTreeClassifier #train
classifier = DecisionTreeClassifier(max_depth=5, random_state =  42)
start = time.time()
classifier.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.029997587203979492s


In [9]:
results =cross_val_score(classifier, x_train, y_train, cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


array([0.52476134, 0.51357804, 0.51148911, 0.51477171, 0.51327962])

In [10]:
np.average(results)

0.5155759617226788

In [11]:
results.std()

0.004711373611412807

### KNN Algorithm

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
start = time.time()
knn= knn.fit(x_train,y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.07702207565307617s


In [15]:
results =cross_val_score(knn, x_train, y_train.values.ravel(), cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


array([0.55519093, 0.53655625, 0.53834676, 0.53595942, 0.54580722])

In [16]:
np.average(results)

0.5423721163276164

In [17]:
results.std()

0.007311257701667285

### SVM Algorithm

In [8]:
from sklearn import svm
svm = svm.SVC() 
start = time.time()
svm.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 18.29585576057434s


In [9]:
results =cross_val_score(svm, x_train, y_train.values.ravel(), cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


array([0.56414081, 0.5681886 , 0.55595345, 0.55237243, 0.56192181])

In [10]:
np.average(results)

0.5605154198262337

In [11]:
results.std()

0.005676602067612734

### Random Forest Algorithm

In [20]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
start = time.time()
rfc.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 4.917866945266724s


In [21]:
results =cross_val_score(rfc, x_train, y_train.values.ravel(), cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


array([0.59874702, 0.59236049, 0.58131901, 0.58579528, 0.58042375])

In [22]:
np.average(results)

0.5877291108912739

In [23]:
results.std()

0.00694321595454817