# Primary-Tumor 

In [1]:
import numpy as np 
import pandas as pd #Verinin okunması ve işlenmesi için pandas kütüphanesi kullanılır
df = pd.read_csv('../dataset/primary-tumor.data')

In [2]:
df.head() 

c1  c2 c3 c4 c5  c6  c7  c8  c9  c10  c11  c12  c13  c14  c15  c16  c17  \
0   1   1  1  ?  3   2   2   1   2    2    2    2    2    2    2    2    2   
1   1   1  1  ?  3   2   2   2   2    2    1    2    2    2    1    2    1   
2   1   1  2  2  3   1   2   2   2    2    2    2    2    2    2    2    1   
3   1   1  2  ?  3   1   2   1   1    2    2    2    2    2    2    2    1   
4   1   1  2  ?  3   1   2   1   1    2    2    2    2    2    2    2    1   

   c18  
0    2  
1    2  
2    2  
3    2  
4    2

### Veri setinin düzenlenmesi

In [3]:
df.drop(['c4'], axis = 1) #Null değer fazla olduğu için bu sütun silinmiştir

c1  c2 c3 c5  c6  c7  c8  c9  c10  c11  c12  c13  c14  c15  c16  c17  c18
0     1   1  1  3   2   2   1   2    2    2    2    2    2    2    2    2    2
1     1   1  1  3   2   2   2   2    2    1    2    2    2    1    2    1    2
2     1   1  2  3   1   2   2   2    2    2    2    2    2    2    2    1    2
3     1   1  2  3   1   2   1   1    2    2    2    2    2    2    2    1    2
4     1   1  2  3   1   2   1   1    2    2    2    2    2    2    2    1    2
..   ..  .. .. ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...
334  22   2  2  ?   2   2   2   2    2    2    2    2    2    2    1    2    2
335  22   2  2  ?   2   2   2   2    2    2    2    2    2    2    1    2    2
336  22   2  2  ?   1   2   2   2    2    2    2    2    2    1    1    2    2
337  22   3  2  2   2   2   2   2    2    2    2    2    1    1    1    2    2
338  22   3  2  2   2   2   2   2    2    2    2    2    2    1    1    2    2

[339 rows x 17 columns]

In [4]:
df = df.replace('?','1') #null değerler dolduruldu

In [5]:
df['c1'].value_counts()

1     84
5     39
18    29
11    28
14    24
22    24
2     20
12    16
7     14
4     14
17    10
3      9
13     7
8      6
19     6
10     2
15     2
20     2
6      1
16     1
21     1
Name: c1, dtype: int64

In [6]:
print("ZeroRule : ",84/df['c1'].value_counts().sum());

ZeroRule :  0.24778761061946902


In [7]:
y = df[['c1']]
X = df.drop(['c1'], axis = 1)

In [8]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [9]:
import time

### Decision Tree Algorithm

In [23]:
from sklearn.tree import DecisionTreeClassifier #train
classifier = DecisionTreeClassifier(max_depth=5, random_state =  42)
start = time.time()
classifier.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.007003068923950195s


In [24]:
results =cross_val_score(classifier, x_train, y_train, cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.45652174, 0.41304348, 0.46666667, 0.4       , 0.26666667])

In [25]:
np.average(results)

0.4005797101449275

In [26]:
results.std()

0.07153374199974759

### KNN Algorithm

In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
start = time.time()
knn= knn.fit(x_train,y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.005997419357299805s


In [28]:
results =cross_val_score(knn, x_train, y_train.values.ravel(), cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.30434783, 0.43478261, 0.48888889, 0.33333333, 0.33333333])

In [29]:
np.average(results)

0.3789371980676328

In [30]:
results.std()

0.07061314831183417

### SVM Algorithm

In [10]:
from sklearn import svm
svm = svm.SVC() 
start = time.time()
svm.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.01700305938720703s


In [11]:
results =cross_val_score(svm, x_train, y_train.values.ravel(), cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.34782609, 0.43478261, 0.53333333, 0.51111111, 0.33333333])

In [12]:
np.average(results)

0.4320772946859903

In [13]:
results.std()

0.08167629292842797

### Random Forest Algorithm

In [33]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
start = time.time()
rfc.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.23901867866516113s


In [34]:
results =cross_val_score(rfc, x_train, y_train.values.ravel(), cv=5) 
results

C:\Users\büşrasalihoğlu\Desktop\notebookvenv\venv\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.34782609, 0.47826087, 0.48888889, 0.37777778, 0.31111111])

In [35]:
np.average(results)

0.4007729468599034

In [36]:
results.std()

0.07090865951268227