# Teaching Assistant Evaluation

In [1]:
import numpy as np 
import pandas as pd #Verinin okunması ve işlenmesi için pandas kütüphanesi kullanılır
df = pd.read_csv('../dataset/tae.data')

In [2]:
df.head() 

c1  c2  c3  c4  c5  c6
0   1  23   3   1  19   3
1   2  15   3   1  17   3
2   1  23   3   2  49   3
3   1   5   2   2  33   3
4   2   7  11   2  55   3

In [3]:
a,b,c = df['c6'].value_counts()
print(a,b,c)

52 50 49


In [4]:
print("Zerorule :",a/(a+b+c)); #ZeroRule hesaplanır

Zerorule : 0.3443708609271523


In [5]:
y = df[['c6']]
X = df.drop(['c6'], axis = 1)

In [6]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [7]:
import time

### Decision Tree Algorithm

In [8]:
from sklearn.tree import DecisionTreeClassifier #train
classifier = DecisionTreeClassifier(max_depth=5, random_state =  42)
start = time.time()
classifier.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.0029993057250976562s


In [9]:
results =cross_val_score(classifier, x_train, y_train, cv=5) 
results

array([0.57142857, 0.45      , 0.5       , 0.25      , 0.6       ])

In [10]:
np.average(results)

0.4742857142857143

In [11]:
results.std()

0.12393217368169326

### KNN Algorithm

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
start = time.time()
knn= knn.fit(x_train,y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.00299835205078125s


In [13]:
results =cross_val_score(knn, x_train, y_train.values.ravel(), cv=5) 
results

array([0.57142857, 0.5       , 0.55      , 0.45      , 0.4       ])

In [14]:
np.average(results)

0.49428571428571433

In [15]:
results.std()

0.0631486745865724

### SVM Algorithm

In [8]:
from sklearn import svm
svm = svm.SVC() 
start = time.time()
svm.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.004010438919067383s


In [9]:
results =cross_val_score(svm, x_train, y_train.values.ravel(), cv=5) 
results

array([0.33333333, 0.4       , 0.3       , 0.3       , 0.3       ])

In [10]:
np.average(results)

0.3266666666666667

In [11]:
results.std()

0.038873012632302015

### Random Forest Algorithm

In [18]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
start = time.time()
rfc.fit(x_train, y_train.values.ravel())
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.28502559661865234s


In [19]:
results =cross_val_score(rfc, x_train, y_train.values.ravel(), cv=5) 
results

array([0.66666667, 0.45      , 0.55      , 0.65      , 0.5       ])

In [20]:
np.average(results)

0.5633333333333334

In [21]:
results.std()

0.08393118874676114