# TIC TAC TOE 

In [1]:
import numpy as np 
import pandas as pd #Verinin okunması ve işlenmesi için pandas kütüphanesi kullanılır
df = pd.read_csv('../dataset/tic-tac-toe.data')

In [2]:
df.head() 

V1 V2 V3 V4 V5 V6 V7 V8 V9       V10
0  x  x  x  x  o  o  x  o  o  positive
1  x  x  x  x  o  o  o  x  o  positive
2  x  x  x  x  o  o  o  o  x  positive
3  x  x  x  x  o  o  o  b  b  positive
4  x  x  x  x  o  o  b  o  b  positive

In [3]:
a,b=df['V10'].value_counts()
print(a,b)

626 332


In [4]:
print("Zerorule :",a/(a+b)) #ZeroRule hesaplanır

Zerorule : 0.6534446764091858


In [5]:
X = pd.get_dummies(df[['V1','V2','V3','V4','V5','V6','V7','V8','V9']],drop_first = True) #encoding işlemi yapılması
df.replace('negative',0,inplace=True)
df.replace('positive',1,inplace=True) 
y = df.iloc[:,9].values 

In [6]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [7]:
import time

### Decision Tree Algorithm

In [24]:
from sklearn.tree import DecisionTreeClassifier #train
classifier = DecisionTreeClassifier(max_depth=10, random_state =  42)
start = time.time()
classifier.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.004993915557861328s


In [25]:
results =cross_val_score(classifier, x_train, y_train, cv=5) 
results

array([0.93023256, 0.921875  , 0.96875   , 0.96875   , 0.9453125 ])

In [26]:
np.average(results)

0.9469840116279069

In [27]:
results.std()

0.01929447646169166

### KNN Algorithm

In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
start = time.time()
knn= knn.fit(x_train,y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.002001047134399414s


In [31]:
results =cross_val_score(knn, x_train, y_train, cv=5) 
results

array([0.98449612, 1.        , 1.        , 0.984375  , 0.953125  ])

In [32]:
np.average(results)

0.9843992248062016

In [33]:
results.std()

0.017116398492817993

### SVM Algorithm

In [8]:
from sklearn import svm
svm = svm.SVC() 
start = time.time()
svm.fit(x_train, y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.030009984970092773s


In [9]:
results =cross_val_score(svm, x_train, y_train, cv=5) 
results

array([0.96899225, 0.9765625 , 1.        , 0.9921875 , 0.984375  ])

In [10]:
np.average(results)

0.9844234496124031

In [11]:
results.std()

0.010980239140026571

### Random Forest Algorithm

In [36]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
start = time.time()
rfc.fit(x_train, y_train)
stop = time.time()
print(f"Train süresi: {stop - start}s")

Train süresi: 0.23100066184997559s


In [37]:
results =cross_val_score(rfc, x_train, y_train, cv=5) 
results

array([0.97674419, 0.96875   , 1.        , 0.9921875 , 0.96875   ])

In [38]:
np.average(results)

0.9812863372093024

In [39]:
results.std()

0.012680592759564133